@startuml
!include C4.iuml!config

System_Boundary(AWS, "AWS") {
    ' could be EC2 or Elastic Beanstalk
    System_Boundary(WebServer, "Web Server") {
        Container(BackendApplication, "Backend Application", "The application coordinating MoPepGen execution")
    }
    System_Ext(SSMConfiguration, "SSM Configuration", "Simple Systems Manager configuration service")
    SystemDb(Database, "Database", "Application storage")
    System_Ext(CloudWatch, "CloudWatch", "Logging service")
    System_Boundary(FrontendApplication, "Website UI") {
        System_Ext(S3Bucket, "S3 Bucket", "Storage for UI components")
        System_Ext(CloudFront, "CloudFront", "CDN to route UI traffic to S3 bucket")
    }

    Rel(BackendApplication, Database, "Uses")
    Rel(BackendApplication, SSMConfiguration, "Uses")
    Rel(BackendApplication, CloudWatch, "Uses")

    Rel(FrontendApplication, WebServer, "Uses")
    Rel_Right(CloudFront, S3Bucket, "Uses")
}

System_Boundary(UCLAHS, "UCLA Health") {
    System_Ext(Okta, "Okta", "User authentication")
    System_Ext(Splunk, "Splunk", "Internal logging service")
    System_Boundary(Cluster, "Cluster") {
        Container(MoPepGen, "MoPepGen", "The MoPepGen pipeline execution system")
    }
    Rel_Left(BackendApplication, MoPepGen, "Uses")
}
Rel(BackendApplication, Splunk, "Uses")
Rel(BackendApplication, Okta, "Uses")


Person(User, "The user of MoPepGen")
Rel(User, FrontendApplication, "Uses")
Rel(User, Okta, "Uses")

@enduml
