@startuml
!theme cerulean-outline
skinparam backgroundColor white
skinparam database {
    backgroundColor transparent
}
skinparam package {
    backgroundColor transparent
}
skinparam dpi 300
skinparam PackageStyle rectangle
!define table($label=" ", $table_name="", $as="") entity "$label" as $as << (T,gray) $table_name >>
!define table($label, $table_name) table($label, $table_name, $table_name)
!define pkey($label) * $label <<pkey, int, not null>>
!define fkey($label, $name, $null="not null") ~ $name <<fkey, int, $null, references $label>>
!define column($label, $type, $extra) {field}+ $label <<$type, $extra>>
!define column($label, $type) {field}+ $label <<$type>>

database "Variant Peptide Annotation" as VariantPeptideAnnotation {
    table(Run, run) {
        pkey(_run_id)
        --
        fkey(plex, _plex_id)
        --
        column(db_id, varchar)
    }

    table(Plex, plex) {
        pkey(_plex_id)
        --
        column(pled_id, varchar)
        column(experiment_type, varchar)
    }

    table(Sample, sample) {
        pkey(_sample_id)
        --
        fkey(plex, _plex_id)
        --
        column(sample_id, varchar)
    }

    table(Peptide, peptide) {
        ' key
        pkey(_peptide_id)
        --
        fkey(run, _run_id)
        --
        column(sequence, varchar)
        column(uuid, varchar)
    }

    table(FastaHeader, fasta_header) {
        pkey(_header_id)
        --
        fkey(peptide, _peptide_id)
        --
        column(header, varchar)
    }

    table(HeaderToInfo, header_to_info) {
        ' key
        pkey(_header_to_info_id)
        --
        fkey(fasta_header, _header_id)
        fkey(info, info_id)
    }

    table(Info, info) {
        pkey(_info_id)
        --
        column(info, varchar)
    }
}

run::_plex_id }|-- plex::_plex_id
plex::_plex_id --|{ sample::_plex_id
run::_run_id --|{ peptide::_run_id
peptide::_peptide_id --|{ fasta_header::_peptide_id
fasta_header::_header_id --|{ header_to_info::_header_id
info::_info_id --|{ header_to_info::_info_id

@enduml
