---
name: Create and publish a Docker image

on:
  workflow_dispatch:
  push:
    branches: ['main']
    tags: ['v*']
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: A job to build and push a docker image
    permissions:
      contents: read
      packages: write
    steps:
      - id: build-push
        uses: uclahs-cds/tool-Docker-action/build-release@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          custom-tags: |
            type=raw,enable=${{github.event_name == 'workflow_dispatch'}},branch=unstable,value=unstable
