---
name: pull_request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - name: test
        uses: docker://python:3.8.5
        run: |
          pip install biopython==1.78 pytest
          pytest
