---
name: pull-request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      msg:
        description: 'Run unit and integration test cases.'
        default: 'This workflow run is triggered by workflow dispatch event'
jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
      
      - name: Install dependencies
        run: |
          pip install biopython==1.78 pytest

      - name: test
        run: |
          pytest
