---
name: pull-request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      msg:
        description: 'Run unit and integration test cases.'
        default: 'This workflow run is triggered by workflow dispatch event'
jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - name: test
        uses: docker://python:3.8.5
        run: |
          pip install biopython==1.78 pytest
          pytest
