---
name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install biopython pathos pytest psutil six matplotlib

      - name: Run Unit Tests
        run: |
          pytest -v -s test/unit

      - name: Run Integration Tests
        run: |
          pytest -v -s test/integration
